# Generated by Django 4.2.3 on 2023-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
