# Generated by Django 4.2.3 on 2023-07-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobapplication_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='name',
        ),
    ]
