# Generated by Django 4.2.3 on 2023-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='job',
            name='company_info',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
