# Generated by Django 4.2.3 on 2023-07-31 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_jobapplication_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='contact',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
