# Generated by Django 4.2.3 on 2023-08-09 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_application_deadline_job_company_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
