# Generated by Django 4.2.3 on 2023-07-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobapplication_contact_jobapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
