# Generated by Django 4.2.3 on 2023-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_company_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recruitment_specialities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_media_links',
            field=models.TextField(blank=True),
        ),
    ]
