# Generated by Django 4.2.3 on 2023-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_client_company_list_user_contact_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='it_skills',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key_skills',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
